name: Python CI

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 取得程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 檢查語法錯誤
        run: python -m py_compile src/*.py
        
      - name: 安裝測試框架（unittest 不需額外安裝）
        run: echo "準備執行測試"

      - name: 執行測試
        run: python -m unittest src/test_main.py
